// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BarManualForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"/admin/fetch-osm\" hx-target=\"#result\" hx-swap=\"innerHTML\" method=\"POST\" class=\"space-y-4 max-w-md\"><div><label for=\"name\" class=\"block\">Navn</label> <input type=\"text\" id=\"name\" name=\"name\" required class=\"w-full border p-2\"></div><div><label for=\"address\" class=\"block\">Adresse</label> <input type=\"text\" id=\"address\" name=\"address\" required class=\"w-full border p-2\"></div><div><label for=\"flyplass\" class=\"block\">Flyplass (0/1, optional)</label> <input type=\"number\" id=\"flyplass\" name=\"flyplass\" min=\"0\" max=\"1\" class=\"w-full border p-2\"></div><div><label for=\"price\" class=\"block\">Pris</label> <input type=\"number\" id=\"price\" name=\"price\" required class=\"w-full border p-2\"></div><div><label for=\"size\" class=\"block\">Str.</label> <input type=\"number\" step=\"0.01\" id=\"size\" name=\"size\" required class=\"w-full border p-2\"></div><div><label for=\"brewery\" class=\"block\">Bryggeri</label> <input type=\"text\" id=\"brewery\" name=\"brewery\" class=\"w-full border p-2\"></div><div><label for=\"orgnummer\" class=\"block\">Orgnummer</label> <input type=\"text\" id=\"orgnummer\" name=\"orgnummer\" required class=\"w-full border p-2\"></div><div><label for=\"osm_id\" class=\"block\">OSM ID</label> <input type=\"text\" id=\"osm_id\" name=\"osm_id\" required class=\"w-full border p-2\"></div><button type=\"submit\" class=\"bg-blue-600 text-white px-4 py-2 rounded\">Fortsett</button></form><div id=\"result\" class=\"mt-4\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
